export const productDataList = [
  {
    id: 1,
    productTitle: "Stylish Handbags",
    category: "women",
    subCategory: "purse",
    brandName: "Mammon",
    pictures: "",
    shortDetails: "Mammon Women's stylish Handbags (LR-bib-blk)",
    description:
      "It contains two shoulder strap so you can carry it a shoulder bag as well lease allow little size deviation because everyone has their own measurement method.",
    rating: 1,
    stock: 16,
    price: 1200.0,
    discount: 50,
    salePrice: 200.15,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: true
  },
  {
    id: 2,
    productTitle: "Leather Formal Shoes",
    category: "men",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 5,
    price: 2220.0,
    discount: 50,
    salePrice: 1200.3,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: true
  },
  {
    id: 3,
    productTitle: "Golden Mirror",
    category: "women",
    subCategory: "goggles",
    brandName: "Vincent",
    pictures: "",
    shortDetails: "Golden Pink Golden Mirror Full Rim Wayfarer Shape",
    description:
      "Golden Pink Golden Mirror Full Rim Wayfarer Shape Medium (Size-53) Vincent Chase NOMADES VC S11109 - C2 Sunglasses",
    rating: 3,
    stock: 23,
    price: 1700.0,
    discount: 50,
    salePrice: 700.0,
    new: false,
    trade: false,
    bestFeature: true,
    sale: false,
    isPopular: false
  },
  {
    id: 4,
    productTitle: "Fastrack Economy 2013",
    category: "men",
    subCategory: "watch",
    brandName: "Fastrack",
    pictures: "",
    shortDetails: "Watch",
    description:
      "Fastrack, a well renowned fashion brand brings an extravagant array of wrist watches for you this season. The Fastrack Economy 2013 Analog Black Dial Men's Watch has brought a significant raised the level of fashion trends in the era of mens accessories. The device is packed with excellent features and new technology to ensure that it gives you the best performance at all times.",
    rating: 5,
    stock: 42,
    price: 3500.0,
    discount: 50,
    salePrice: 2800.0,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: false
  },
  {
    id: 5,
    productTitle: "Digital Still Camera",
    category: "electric",
    subCategory: "camera",
    brandName: "philips",
    pictures: "",
    shortDetails: "Watch",
    description:
      "The ESee digital still camera lets you make high quality panorama pictures with photo stitching and captures 8 times closer to action with optical zoom. Get video in great details and make perfect shot with auto mode.",
    rating: 3,
    stock: 12,
    price: 55000.0,
    discount: 50,
    salePrice: 80000.0,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false
  },
  {
    id: 6,
    productTitle: "Boat Headphones",
    category: "electric",
    subCategory: "Headphones",
    brandName: "boat",
    pictures: "",
    shortDetails: "Boat Rockerz 400 On-Ear Bluetooth Headphones (Carbon Black)",
    description:
      "Now just stop worrying about wires hanging from here and there. Wired is passé. Foldable/ Collapsible: Designed for people always on the move, easy storage and easy to carry. ",
    rating: 0,
    stock: 43,
    price: 1400.0,
    discount: 50,
    salePrice: 700.0,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false
  },
  {
    id: 7,
    productTitle: "Anolog Men's Watch",
    category: "men",
    subCategory: "watch",
    brandName: "swisstyle",
    pictures: "",
    shortDetails: "Swisstyle Anolog Black Dial Men's Watch-SS-GR06612-BLK-CH",
    description: "Swisstyle Anolog Black Dial Men's Watch-SS-GR06612-BLK-CH",
    rating: 5,
    stock: 12,
    price: 7000.0,
    discount: 50,
    salePrice: 6700.0,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: false,

    colors: []
  },
  {
    id: 8,
    productTitle: "Black Leisure Shorts",
    category: "men",
    subCategory: "clothes",
    brandName: "jockey",
    pictures: "",
    shortDetails: "jockey graphite & black leisure shorts",
    description:
      "Fabric Details : 80% Cotton, 20% Polyester Premium Combed Cotton Rich fabric Straight Fit Durable broad waistband with flat inner drawstring",
    rating: 5,
    stock: 75,
    price: 2000.0,
    discount: 50,
    salePrice: 1300.0,
    new: false,
    trade: false,
    bestFeature: true,
    sale: false,
    isPopular: true
  },
  {
    id: 9,
    productTitle: "Men's V Neck Cotton T-Shirts",
    category: "all",
    subCategory: "clothes",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 54,
    price: 45,
    discount: 50,
    salePrice: 40,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false
  },
  {
    id: 10,
    productTitle: "Round Neck Full Sleeves T-Shirt",
    category: "all",
    subCategory: "clothes",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 3,
    price: 100,
    discount: 2,
    salePrice: 90,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: true
  },
  {
    id: 11,
    productTitle: "Overdyed Cargo Utility Shorts",
    category: "all",
    subCategory: "clothes",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 8,
    price: 240,
    discount: 23,
    salePrice: 200,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false
  },
  {
    id: 12,
    productTitle: "Winter T-Shirts For Mens",
    category: "all",
    subCategory: "clothes",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 0,
    stock: 13,
    price: 254,
    discount: 50,
    salePrice: 200,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: true
  },
  {
    id: 13,
    productTitle: "Men's Cotton T-Shirt",
    category: "all",
    subCategory: "clothes",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 7,
    price: 100,
    discount: 50,
    salePrice: 50,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false
  },
  {
    id: 14,
    productTitle: "Men's Cotton Hooded T-Shirt",
    category: "all",
    subCategory: "clothes",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 12,
    price: 25,
    discount: 50,
    salePrice: 23,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: true
  },
  {
    id: 15,
    productTitle: "Men's Cotton T-Shirt",
    category: "all",
    subCategory: "clothes",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 12,
    price: 45,
    discount: 50,
    salePrice: 40,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false
  },
  {
    id: 16,
    productTitle: "Women's Crepe Jumpsuit",
    category: "all",
    subCategory: "clothes",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 3,
    stock: 55,
    price: 9000,
    discount: 50,
    salePrice: 8500,
    new: false,
    trade: false,
    bestFeature: true,
    sale: false,
    isPopular: false
  },
  {
    id: 17,
    productTitle: "Men's Brown Sandals",
    category: "all",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 77,
    price: 111,
    discount: 50,
    salePrice: 100,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["New"]
  },
  {
    id: 18,
    productTitle: "Strap Slingback Sandals",
    category: "all",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 32,
    price: 100,
    discount: 20,
    salePrice: 80,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 19,
    productTitle: "Rubber Clogs For Men",
    category: "all",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 5,
    stock: 12,
    price: 85,
    discount: 12,
    salePrice: 70,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Best Feature"]
  },
  {
    id: 20,
    productTitle: "Converse Unisex Sneakers",
    category: "all",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 8,
    price: 190,
    discount: 12,
    salePrice: 180,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 21,
    productTitle: "Under Armour Men's Shoes",
    category: "all",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 4,
    price: 400,
    discount: 50,
    salePrice: 350,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 22,
    productTitle: "Slingback Heeled Sandals",
    category: "all",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 1,
    stock: 2,
    price: 200,
    discount: 50,
    salePrice: 220,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Trade"]
  },
  {
    id: 23,
    productTitle: "Slip-on Gusset Shoes",
    category: "all",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 3,
    stock: 6,
    price: 285,
    discount: 50,
    salePrice: 250,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 24,
    productTitle: "Shoes For Men & Boys",
    category: "all",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 44,
    price: 400,
    discount: 50,
    salePrice: 300,
    new: false,
    trade: false,
    bestFeature: true,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 25,
    productTitle: "Cold Whole Juicer",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 23,
    price: 120,
    discount: 50,
    salePrice: 100,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["New"]
  },
  {
    id: 26,
    productTitle: "Vegetable Plants",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 56,
    price: 6800,
    discount: 50,
    salePrice: 6000,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 27,
    productTitle: "Tea Kettle With Cups",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 345,
    price: 6900,
    discount: 50,
    salePrice: 6400,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Best Feature"]
  },
  {
    id: 28,
    productTitle: "Wooden Spoon",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 4,
    price: 450,
    discount: 50,
    salePrice: 350,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 29,
    productTitle: "Tea Plant",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 1,
    stock: 456,
    price: 100,
    discount: 50,
    salePrice: 80,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 30,
    productTitle: "Plastic Small Bowl",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 45,
    price: 68,
    discount: 50,
    salePrice: 60,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Trade"]
  },
  {
    id: 31,
    productTitle: "Plastic Box",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 345,
    price: 95,
    discount: 50,
    salePrice: 80,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 32,
    productTitle: "Silver Spoon",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 34,
    price: 400,
    discount: 50,
    salePrice: 450,
    new: false,
    trade: false,
    bestFeature: true,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 33,
    productTitle: "Smart Video Camera",
    category: "all",
    subCategory: "accessories",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 1,
    price: 7500,
    discount: 50,
    salePrice: 7000,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["New"]
  },
  {
    id: 34,
    productTitle: "Mobile Back Cover",
    category: "all",
    subCategory: "accessories",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 6,
    price: 9000,
    discount: 50,
    salePrice: 8500,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 35,
    productTitle: "Smart Watch",
    category: "all",
    subCategory: "accessories",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 2,
    price: 6500,
    discount: 50,
    salePrice: 6000,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Best Feature"]
  },
  {
    id: 36,
    productTitle: " Mobile Cover",
    category: "all",
    subCategory: "accessories",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 56,
    price: 12000,
    discount: 50,
    salePrice: 11500,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 37,
    productTitle: "HeadPhone",
    category: "all",
    subCategory: "accessories",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 1,
    stock: 3,
    price: 9999,
    discount: 50,
    salePrice: 8888,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 38,
    productTitle: "Lens For Mobile",
    category: "all",
    subCategory: "accessories",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 5,
    price: 7777,
    discount: 50,
    salePrice: 6666,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Trade"]
  },
  {
    id: 39,
    productTitle: " Men's Watch",
    category: "all",
    subCategory: "accessories",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 5,
    stock: 3,
    price: 5555,
    discount: 50,
    salePrice: 4444,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 40,
    productTitle: "Polaroid 300 Instant Camera",
    category: "all",
    subCategory: "accessories",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 1,
    stock: 4,
    price: 6800,
    discount: 40,
    salePrice: 6000,
    new: false,
    trade: false,
    bestFeature: true,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 41,
    productTitle: "Dining Table",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 1,
    stock: 654,
    price: 9400,
    discount: 12,
    salePrice: 9000,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["New"]
  },
  {
    id: 42,
    productTitle: "Day Bed",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 45,
    price: 7800,
    discount: 40,
    salePrice: 7000,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 43,
    productTitle: "Black Fabric Seat Sofa",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 756,
    price: 9000,
    discount: 40,
    salePrice: 8500,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Best Feature"]
  },
  {
    id: 44,
    productTitle: "Dura Comfort Stool",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 56,
    price: 9000,
    discount: 12,
    salePrice: 8500,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 45,
    productTitle: "Plastic Dining Table",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 567,
    price: 1258,
    discount: 2,
    salePrice: 1200,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 46,
    productTitle: "Chair",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 34,
    price: 6500,
    discount: 10,
    salePrice: 6000,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Trade"]
  },
  {
    id: 47,
    productTitle: "Outdoor Table",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 324,
    price: 17000,
    discount: 40,
    salePrice: 15000,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 48,
    productTitle: "Modern Sofa",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 345,
    price: 94000,
    discount: 25,
    salePrice: 88000,
    new: false,
    trade: false,
    bestFeature: true,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 49,
    productTitle: "Daily Wear Shoes",
    category: "men",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 5,
    stock: 345,
    price: 1000.0,
    discount: 50,
    salePrice: 700.0,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 50,
    productTitle: "Sports Gray Shoes",
    category: "men",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 1,
    stock: 23,
    price: 25000.0,
    discount: 50,
    salePrice: 24000.0,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 51,
    productTitle: "Party Wear Shoes",
    category: "men",
    subCategory: "footwear",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 72,
    price: 8000.0,
    discount: 50,
    salePrice: 5000.0,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 52,
    productTitle: "Day Bed",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 5,
    stock: 45,
    price: 10000,
    discount: 10,
    salePrice: 9000,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 53,
    productTitle: "Modern Sofa",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 345,
    price: 2500,
    discount: 7,
    salePrice: 2300,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 54,
    productTitle: "Chair",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 5,
    stock: 34,
    price: 6500,
    discount: 10,
    salePrice: 6000,
    new: false,
    trade: false,
    bestFeature: false,
    sale: true,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Trade"]
  },
  {
    id: 55,
    productTitle: "Dining Table",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 1,
    stock: 654,
    price: 3333,
    discount: 10,
    salePrice: 2222,
    new: false,
    trade: false,
    bestFeature: true,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"],
    tags: ["New"]
  },
  {
    id: 56,
    productTitle: "Outdoor Table",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 324,
    price: 17000,
    discount: 23,
    salePrice: 15000,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 57,
    productTitle: "Black Fabric Seat Sofa",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 756,
    price: 9777,
    discount: 40,
    salePrice: 8777,
    new: false,
    trade: false,
    bestFeature: false,
    sale: true,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Best Feature"]
  },
  {
    id: 58,
    productTitle: "Plastic Dining Table",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 3,
    stock: 12,
    price: 245,
    discount: 72,
    salePrice: 145,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 59,
    productTitle: "Dura Comfort Stool",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 13,
    price: 9000,
    discount: 12,
    salePrice: 8500,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 60,
    productTitle: "Day Bed",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 45,
    price: 2345,
    discount: 23,
    salePrice: 1234,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 61,
    productTitle: "Modern Sofa",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 345,
    price: 345,
    discount: 25,
    salePrice: 234,
    new: false,
    trade: false,
    bestFeature: true,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 62,
    productTitle: "Dining Table",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 1,
    stock: 654,
    price: 3333,
    discount: 33,
    salePrice: 2222,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["New"]
  },
  {
    id: 63,
    productTitle: "Chair",
    category: "all",
    subCategory: "furniture",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 34,
    price: 6500,
    discount: 10,
    salePrice: 6000,
    new: false,
    trade: false,
    bestFeature: true,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Trade"]
  },
  {
    id: 64,
    productTitle: "Cold Whole Juicer",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 3,
    stock: 2,
    price: 8500,
    discount: 50,
    salePrice: 6500,
    new: true,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"],
    tags: ["New"]
  },
  {
    id: 65,
    productTitle: "Vegetable Plants",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 56,
    price: 2345,
    discount: 50,
    salePrice: 1234,
    new: false,
    trade: false,
    bestFeature: false,
    sale: true,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 66,
    productTitle: "Tea Kettle With Cups",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 345,
    price: 123,
    discount: 12,
    salePrice: 100,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Best Feature"]
  },
  {
    id: 67,
    productTitle: "Wooden Spoon",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 2,
    stock: 3,
    price: 2300,
    discount: 50,
    salePrice: 2000,
    new: false,
    trade: false,
    bestFeature: true,
    sale: false,
    isPopular: true,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 68,
    productTitle: "Tea Plant",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 34,
    price: 6000,
    discount: 50,
    salePrice: 5500,
    new: false,
    trade: true,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"]
  },
  {
    id: 69,
    productTitle: "Plastic Small Bowl",
    category: "all",
    subCategory: "kitchen",
    brandName: "Lee Cooper",
    pictures: "",
    shortDetails: "Lee Cooper Men's Lc1461eblack Leather Formal Shoes",
    description:
      "Experiment with style by wearing this pair of formal shoes from the coveted brand, Lee Cooper. It is crafted from superior quality material that makes it long lasting. Besides, the lace up fastening that makes it convenient to wear.",
    rating: 4,
    stock: 45,
    price: 3400,
    discount: 12,
    salePrice: 3000,
    new: false,
    trade: false,
    bestFeature: false,
    sale: false,
    isPopular: false,
    size: ["6UK", "7UK", "8UK"],
    tags: ["Trade"]
  }
];

export default {
  productDataList
};
